# Build - Build necessary JS files
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - build
  - deploy

# Job: Build
# Installs npm packages, transpiles ES6 -> ES5
# Passes package.json node_modules/ and build/ onto next steps using artifacts
build:
  image: node:8.4.0
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - package.json
      - node_modules/
      - build/
  tags:
    - app

# Job: Deploy
# Zips the contents of our built application, uploads to S3
# Configures a new Elastic Beanstalk version and switches to that version
deploy:
  image: python:latest
  stage: deploy
  script:
    - chmod +x ./bin/deploy
    - ./bin/deploy
  tags:
    - app